params = Dict{Symbol,Any}()
params[:subject] = "sub01"
params[:slices] = [1,3,5,7] # nothing for all slices
params[:echoes] = [5] # nothing for all echoes
params[:rep] = 0
params[:reconstruct_map] = true
params[:comp_sensit] = true
params[:comp_centerline] = true
params[:trust_SCT] = false
params[:use_centerline] = true
params[:corr_type] = "FFT_unwrap"
params[:FFT_interval] = 35 # millimiters
params[:mask_thresh] = 0.05
params[:root_path] = "/Users/laurabeghini/Desktop/files/" #"WRITE YOUR ROOT PHATH HERE"

params[:lable] = params[:corr_type] * "_rep_" * string(params[:rep])
params[:path_imgData] = params[:root_path] * params[:subject] * "/h5/GRE_PS.h5"
params[:path_refData] = params[:root_path] * params[:subject] * "/h5/GRE_ref.h5"
params[:path_niftiMap] = params[:root_path] * params[:subject] * "/Nifti/GRE_ref.nii"
params[:path_centerline] = params[:root_path] * params[:subject] * "/Nifti/"
params[:path_physio] = params[:root_path] * params[:subject] * "/Physiological_trace/resp.mat"
params[:path_sensit] = params[:root_path] * params[:subject] * "/Results/MapEspirit_GRE_0p5.jld2"
params[:path_noise] = params[:root_path] * params[:subject] * "/Results/noisemat.jld2"
params[:path_results] = params[:root_path] * params[:subject] * "/Results/"
file_name = split(params[:path_imgData], "/")
file_name = last(file_name)
file_name = split(file_name, "_2.h5")
params[:file_name] = first(file_name)